### ISSUE TITLE
Possible to obtain Gamertag's email?

### ISSUE THREAD

**Issue by pfeiferchristopher** [xboxapi/XboxAPI-Example-Code#2]
I'm trying to figure out a way to verify someone is in fact the owner of a gamertag before I allow them to attach it to their local account on my site. But unless I can get a Gamertag's email address for their Microsoft LIVE account I can not do this.

I have OAuth implemented for Microsoft already so I can have them link that to get their Microsoft account's email, but unless the XboxAPI can return a Gamester's account's email address I can not confirm them.

If I'm not able to confirm them I'll have to setup some sort of "Report this Gamertag as mine" system for when someone adds someone else's Gamertag to their account.

**Comment by djekl** [comment]
Unfortunately the API does not return the email address of a gamertag.

If your looking to validate a profile, then do it like the other sites and ask the user to change (or add something to) the bio. Then you can check this unique code is present etc.

**Comment by pfeiferchristopher** [comment]
Ah thank you. I will implement that verification method as well as the reporting methods.
