### ISSUE TITLE
Problem getting Gamertag via Xuid

### ISSUE THREAD

**Issue by pfeiferchristopher** [xboxapi/XboxAPI-Example-Code#3]
Hello, first off let me say that thank you for all the hard work I know has been put into this API it has literally given me so many possibilities.

I have built a wrapper for Laravel 5.0 that I will use to access the API. It implements GuzzleHttp Requests to get the info, sending api key, etc but I am having an issue with the `/v2/gamertag/{xuid}` part of your API.

When I visit the url via my browser I get my gamertag no problem. But when I get it via Guzzle and then I receive a Guzzle Stream as the body, and if I attempt `$res->json()` as I do with most of the other responses in order to build a PHP collection I get an error about it being malformed json even tho this same method works just fine on the `/v2/xuid/{gamertag}` endpoint which also only prints plain text response.

I know this isn't really your problem I guess, but I'm looking for any pointers. I can work without the ID > Gamertag function but I'd like to have it.

**Comment by djekl** [comment]
Both endpoints ```/v2/xuid/{gamertag}``` and ```/v2/gamertag/{xuid}``` return plain text, not JSON. This is where you will be getting issues.

**Comment by pfeiferchristopher** [comment]
I understand that the that's where '->getBody()' is supposed to be used but
I only get the Guzzle Stream object was wondering if had any idea why.

**Comment by djekl** [comment]
I unfortunately don't understand why you are getting the issue. If you can provide me some example code I may be able to help further.

**Comment by pfeiferchristopher** [comment]
Yeah I think I figured it out. Probably was a easier way since its just
plain text lol
